##
## EPITECH PROJECT, 2022
## makefile
## File description:
## makefile
##

SRC1	=	antman/

SRC2	=	giantman/

all:
	make -C $(SRC1)
	make -C $(SRC2)

clean:
	make clean -C $(SRC1)
	make clean -C $(SRC2)

fclean:
	make fclean -C $(SRC1)
	make fclean -C $(SRC2)

re:
	make re -C $(SRC1)
	make re -C $(SRC2)
